### ISSUE TITLE
Support for VS 2022 Preview 1

### ISSUE THREAD

**Issue by yannduran** [olegtarasov/VSIconizer#9]
Hi Oleg,

I love, Love, LOVE your extension! I've been using it for years. Thank you so much for creating this extension!!! 

Are you able to add support for VS 2022 Preview 1? It's driving me nuts to have all the tabs display text instead of their icons.

It's such an essential feature that it really should be an option in VS itself. That way there wouldn't be a bit of lag in showing the icons sometimes. 

It's no fault of your extension, because I know that you don't the ability to load at the same time as the IDE. It can only load **_after_** the IDE is displayed and VS starts to load extensions. Even if it's an async extension there's no autoload guid to load **_with_** the IDE, only after it's displayed itself.

**Comment by olegtarasov** [comment]
Hi @yannduran! Yes, I plan to install VS 2022 preview in a couple of days and figure out what's needed in order to support it.

The problem with icons not showing immediately is actually not related to async loading. In order to show icons, I need to modify WPF component tree, which can be reset to its initial state by Visual Studio at any time. Unfortunately, I have no easy way of intercepting this event, so all I can do is monitor the tree every second and apply modifications when necessary. Hence the visible lag in showing icons.

**Comment by olegtarasov** [comment]
Hi @yannduran! You can try the new version that supports VS 2022: https://marketplace.visualstudio.com/items?itemName=OlegTarasov.Iconizer2022. Unfortunately, I couldn't figure out a way to make single package for VS 2017-2022.

**Comment by yannduran** [comment]
It's working great Oleg! Thank you very much for doing this so quickly.
